service_name: 'c8cf1555-d905-4818-971d-0f59f4190479'

http:
  url: http://0.0.0.0:9000
  cors:
    access_control_allow_headers:
      - Content-Type
      - Cache-Control
      - Authorization
      - X-Total-Count
    access_control_allow_origin:
      - https://go2.uiscom.ru

uc_flow_node:
  register_on_start: false
  execute_view_queue_size: 500
  execute_view_workers: 5
  private_url: https://f7e6-2a03-d000-1484-117c-70c6-5293-9b90-bfae.ngrok-fre
  public_url: https://f7e6-2a03-d000-1484-117c-70c6-5293-9b90-bfae.ngrok-fre
  uc_flow:
    domain: https://uc-flow-v2-pp-api.uis.ru
    jwt_secret: 9109a79d-74f9-45bd-b369-5e7a885421e5s
